name: Build Standalone (Nuitka)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: "3.14.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build with Nuitka
        run: |
          python -m nuitka --standalone --windows-icon-from-ico=dnd_logo.ico --output-filename=DnD_Time_Manager DnD_Time_Manager.py --enable-plugin=tk-inter --assume-yes-for-downloads --output-dir=build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DnD_Time_Manager
          path: build\DnD_Time_Manager.dist
